import type { CatalogItem, Category, ConfigItem, Machine } from "./types";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "system", label: "Система" },
  { id: "drivers", label: "Драйверы" },
  { id: "browsers", label: "Браузеры" },
  { id: "comms", label: "Связь" },
  { id: "media", label: "Медиа" },
  { id: "create", label: "Работа" },
  { id: "tools", label: "Утилиты" },
  { id: "games", label: "Игры" },
  { id: "vendor", label: "Только файлом" },
];

export const DEFAULT_MACHINE: Machine = {
  name: "F33LG88D",
  vpnEnabled: true,
  vpnExe: "G:\\VPN\\v2rayN-windows-64\\v2rayN.exe",
  vpnWait: 25,
  desktopShortcut: true,
  reboot: false,
  tweaks: true,
  windowsUpdateDrivers: true,
};

export const CATALOG: CatalogItem[] = [
  {
    id: "vcredist",
    name: "Visual C++ Redistributable",
    blurb: "Нужен почти всему. Ставится первым.",
    category: "system",
    source: "winget",
    wingetId: "Microsoft.VCRedist.2015+.x64",
    defaultOn: true,
  },
  {
    id: "dotnet8",
    name: ".NET 8 Desktop Runtime",
    blurb: "FanControl и часть утилит без него не стартуют.",
    category: "system",
    source: "winget",
    wingetId: "Microsoft.DotNet.DesktopRuntime.8",
    defaultOn: true,
  },
  {
    id: "temurin",
    name: "Temurin JRE 21",
    blurb: "Вместо мёртвого Oracle JRE — актуальный Adoptium.",
    category: "system",
    source: "winget",
    wingetId: "EclipseAdoptium.Temurin.21.JRE",
    defaultOn: true,
  },
  {
    id: "7zip",
    name: "7-Zip",
    blurb: "Архивы без пробного срока WinRAR.",
    category: "system",
    source: "winget",
    wingetId: "7zip.7zip",
    defaultOn: true,
  },
  {
    id: "winrar",
    name: "WinRAR",
    blurb: "Если привычка важнее лицензии.",
    category: "system",
    source: "winget",
    wingetId: "RARLab.WinRAR",
    defaultOn: true,
  },
  {
    id: "amd-gpu",
    name: "AMD Adrenalin — RX 6800",
    blurb: "AMD режет прямые ссылки. Скачай установщик с сайта и положи в drivers.",
    category: "drivers",
    source: "dropin",
    dir: "drivers",
    match: "*Adrenalin*.exe",
    args: "-INSTALL -SILENT",
    page: "https://www.amd.com/en/support/download/drivers.html",
    defaultOn: true,
    note: "Официальный сайт AMD → Graphics → скачать Adrenalin. Не зеркала.",
  },
  {
    id: "amd-chipset",
    name: "AMD Chipset",
    blurb: "Чипсет с amd.com, не из случайного ZIP.",
    category: "drivers",
    source: "dropin",
    dir: "drivers",
    match: "*Chipset*.exe",
    args: "/S",
    page: "https://www.amd.com/en/support/download/drivers.html",
    defaultOn: true,
  },
  {
    id: "realtek-audio",
    name: "Realtek HD Audio",
    blurb: "С страницы материнки Gigabyte. URL у них живёт недели.",
    category: "drivers",
    source: "dropin",
    dir: "drivers",
    match: "*Audio*.exe",
    page: "https://www.gigabyte.com/Support",
    defaultOn: true,
  },
  {
    id: "realtek-lan",
    name: "Realtek LAN",
    blurb: "Тот же Support Gigabyte → LAN.",
    category: "drivers",
    source: "dropin",
    dir: "drivers",
    match: "*LAN*.exe",
    page: "https://www.gigabyte.com/Support",
    defaultOn: true,
  },
  {
    id: "intel-wifi",
    name: "Intel Wi-Fi",
    blurb: "Windows Update обычно ставит сам. Файл — запасной путь.",
    category: "drivers",
    source: "windows-update",
    dir: "drivers",
    match: "*WiFi*.exe",
    page: "https://www.gigabyte.com/Support",
    defaultOn: true,
  },
  {
    id: "intel-bt",
    name: "Intel Bluetooth",
    blurb: "Как Wi-Fi: сначала Windows Update, иначе файл из Support.",
    category: "drivers",
    source: "windows-update",
    dir: "drivers",
    match: "*Bluetooth*.exe",
    page: "https://www.gigabyte.com/Support",
    defaultOn: true,
  },
  {
    id: "chrome",
    name: "Google Chrome",
    blurb: "Ставится через winget, без ручного exe.",
    category: "browsers",
    source: "winget",
    wingetId: "Google.Chrome",
    defaultOn: true,
  },
  {
    id: "firefox",
    name: "Firefox",
    blurb: "Запасной браузер.",
    category: "browsers",
    source: "winget",
    wingetId: "Mozilla.Firefox",
    defaultOn: true,
  },
  {
    id: "operagx",
    name: "Opera GX",
    blurb: "Как в исходном списке.",
    category: "browsers",
    source: "winget",
    wingetId: "Opera.OperaGX",
    defaultOn: true,
  },
  {
    id: "discord",
    name: "Discord",
    blurb: "Пользовательская установка из-под UAC твоего аккаунта.",
    category: "comms",
    source: "winget",
    wingetId: "Discord.Discord",
    defaultOn: true,
  },
  {
    id: "telegram",
    name: "Telegram",
    blurb: "Десктопный клиент.",
    category: "comms",
    source: "winget",
    wingetId: "Telegram.TelegramDesktop",
    defaultOn: true,
  },
  {
    id: "vlc",
    name: "VLC",
    blurb: "Плеер на случай, если K-Lite не нужен.",
    category: "media",
    source: "winget",
    wingetId: "VideoLAN.VLC",
    defaultOn: true,
  },
  {
    id: "klite",
    name: "K-Lite Codec Pack Full",
    blurb: "Full, не Mega: у Full стабильный пакет в winget. Ссылка на codecguide не нужна.",
    category: "media",
    source: "winget",
    wingetId: "CodecGuide.K-LiteCodecPack.Full",
    defaultOn: true,
  },
  {
    id: "xnview",
    name: "XnView MP",
    blurb: "Просмотр изображений.",
    category: "media",
    source: "winget",
    wingetId: "XnSoft.XnViewMP",
    defaultOn: true,
  },
  {
    id: "vscode",
    name: "VS Code",
    blurb: "Редактор.",
    category: "create",
    source: "winget",
    wingetId: "Microsoft.VisualStudioCode",
    defaultOn: true,
  },
  {
    id: "git",
    name: "Git",
    blurb: "CLI git.",
    category: "create",
    source: "winget",
    wingetId: "Git.Git",
    defaultOn: true,
  },
  {
    id: "python",
    name: "Python 3.12",
    blurb: "3.12 вместо застывшего 3.11 из старого скрипта.",
    category: "create",
    source: "winget",
    wingetId: "Python.Python.3.12",
    defaultOn: true,
  },
  {
    id: "notepadpp",
    name: "Notepad++",
    blurb: "Быстрый текстовый.",
    category: "create",
    source: "winget",
    wingetId: "Notepad++.Notepad++",
    defaultOn: true,
  },
  {
    id: "libreoffice",
    name: "LibreOffice",
    blurb: "Офис без подписки.",
    category: "create",
    source: "winget",
    wingetId: "TheDocumentFoundation.LibreOffice",
    defaultOn: true,
  },
  {
    id: "acrobat",
    name: "Acrobat Reader",
    blurb: "PDF.",
    category: "create",
    source: "winget",
    wingetId: "Adobe.Acrobat.Reader.64-bit",
    defaultOn: true,
  },
  {
    id: "filezilla",
    name: "FileZilla",
    blurb: "FTP. Id: FileZilla.FileZilla, не .Client.",
    category: "create",
    source: "winget",
    wingetId: "FileZilla.FileZilla",
    defaultOn: true,
  },
  {
    id: "putty",
    name: "PuTTY",
    blurb: "SSH на крайний случай.",
    category: "create",
    source: "winget",
    wingetId: "PuTTY.PuTTY",
    defaultOn: true,
  },
  {
    id: "winscp",
    name: "WinSCP",
    blurb: "SFTP с окнами.",
    category: "create",
    source: "winget",
    wingetId: "WinSCP.WinSCP",
    defaultOn: true,
  },
  {
    id: "mobaxterm",
    name: "MobaXterm",
    blurb: "Есть в winget. Скачивать ZIP с mobatek.net скрипту незачем.",
    category: "create",
    source: "winget",
    wingetId: "Mobatek.MobaXterm",
    defaultOn: true,
  },
  {
    id: "ollama",
    name: "Ollama",
    blurb: "Локальные модели.",
    category: "create",
    source: "winget",
    wingetId: "Ollama.Ollama",
    defaultOn: true,
  },
  {
    id: "fancontrol",
    name: "FanControl",
    blurb: "Rem0o.FanControl в winget. GitHub ZIP больше не нужен.",
    category: "tools",
    source: "winget",
    wingetId: "Rem0o.FanControl",
    defaultOn: true,
  },
  {
    id: "proxifier",
    name: "Proxifier",
    blurb: "VentoByte.Proxifier. Лицензию кладёшь сам.",
    category: "tools",
    source: "winget",
    wingetId: "VentoByte.Proxifier",
    defaultOn: true,
  },
  {
    id: "everything",
    name: "Everything",
    blurb: "Мгновенный поиск файлов.",
    category: "tools",
    source: "winget",
    wingetId: "voidtools.Everything",
    defaultOn: true,
  },
  {
    id: "greenshot",
    name: "Greenshot",
    blurb: "Скриншоты.",
    category: "tools",
    source: "winget",
    wingetId: "Greenshot.Greenshot",
    defaultOn: true,
  },
  {
    id: "revo",
    name: "Revo Uninstaller",
    blurb: "Правильный id: RevoUninstaller.RevoUninstaller.",
    category: "tools",
    source: "winget",
    wingetId: "RevoUninstaller.RevoUninstaller",
    defaultOn: true,
  },
  {
    id: "ccleaner",
    name: "CCleaner",
    blurb: "Piriform.CCleaner. Можно выключить, если не доверяешь.",
    category: "tools",
    source: "winget",
    wingetId: "Piriform.CCleaner",
    defaultOn: true,
  },
  {
    id: "crystal",
    name: "CrystalDiskInfo",
    blurb: "SMART дисков.",
    category: "tools",
    source: "winget",
    wingetId: "CrystalDewWorld.CrystalDiskInfo",
    defaultOn: true,
  },
  {
    id: "hwmonitor",
    name: "HWMonitor",
    blurb: "Температуры.",
    category: "tools",
    source: "winget",
    wingetId: "CPUID.HWMonitor",
    defaultOn: true,
  },
  {
    id: "keepassxc",
    name: "KeePassXC",
    blurb: "KeePassX мёртв. Старый id KeePassX.KeePassX ставить нельзя.",
    category: "tools",
    source: "winget",
    wingetId: "KeePassXCTeam.KeePassXC",
    defaultOn: true,
  },
  {
    id: "qbittorrent",
    name: "qBittorrent",
    blurb: "Торренты.",
    category: "tools",
    source: "winget",
    wingetId: "qBittorrent.qBittorrent",
    defaultOn: true,
  },
  {
    id: "steam",
    name: "Steam",
    blurb: "Магазин Valve.",
    category: "games",
    source: "winget",
    wingetId: "Valve.Steam",
    defaultOn: true,
  },
  {
    id: "epic",
    name: "Epic Games Launcher",
    blurb: "Epic.",
    category: "games",
    source: "winget",
    wingetId: "EpicGames.EpicGamesLauncher",
    defaultOn: true,
  },
  {
    id: "rgb-fusion",
    name: "RGB Fusion",
    blurb: "Утилита Gigabyte. В winget нет — только файл с Support.",
    category: "vendor",
    source: "dropin",
    dir: "installers",
    match: "*RGB*Fusion*.exe",
    page: "https://www.gigabyte.com/Support",
    defaultOn: true,
  },
  {
    id: "acronis",
    name: "Acronis Disk Director",
    blurb: "Платный продукт. Прямой exe с acronis.com скрипт не угадает.",
    category: "vendor",
    source: "dropin",
    dir: "installers",
    match: "*Acronis*.exe",
    page: "https://www.acronis.com",
    defaultOn: true,
  },
  {
    id: "monect",
    name: "PC Remote / Monect",
    blurb: "Приёмник с monect.com.",
    category: "vendor",
    source: "dropin",
    dir: "installers",
    match: "*Monect*.exe",
    page: "https://www.monect.com",
    defaultOn: true,
  },
  {
    id: "focusrite",
    name: "Focusrite Control",
    blurb: "CDN-ссылки с версией в имени протухают. Бери с focusrite.com.",
    category: "vendor",
    source: "dropin",
    dir: "installers",
    match: "*Focusrite*.exe",
    page: "https://focusrite.com/downloads",
    defaultOn: true,
  },
  {
    id: "assistent",
    name: "Ассистент",
    blurb: "Только установщик с assistent.ru.",
    category: "vendor",
    source: "dropin",
    dir: "installers",
    match: "*Assistent*.exe",
    page: "https://assistent.ru",
    defaultOn: true,
  },
];

export const CONFIGS: ConfigItem[] = [
  {
    id: "fancontrol-config",
    name: "FanControl",
    from: "configs/FanControl/FanControl.config",
    to: "%APPDATA%\\FanControl\\FanControl.config",
    hint: "Экспортируй свой профиль кривых и положи файл сюда.",
    defaultOn: true,
  },
  {
    id: "amd-profile",
    name: "AMD Adrenalin profile",
    from: "configs/AMD_Adrenalin/my_rx6800_profile.zip",
    to: "%USERPROFILE%\\Documents\\AMD\\Profiles\\my_rx6800_profile.zip",
    hint: "ZIP профиля из Adrenalin. Скрипт только копирует, не импортирует в GPU.",
    defaultOn: true,
  },
  {
    id: "v2rayn-config",
    name: "v2rayN",
    from: "configs/v2rayN/f33lg88d",
    to: "VPN_WORKDIR",
    hint: "Конфиг/папка подписки. Копируется в каталог v2rayN, не в корень G:\\.",
    defaultOn: true,
  },
];

export function defaultEnabled(): Record<string, boolean> {
  const map: Record<string, boolean> = {};
  for (const item of CATALOG) map[item.id] = item.defaultOn;
  return map;
}

export function defaultConfigs(): Record<string, boolean> {
  const map: Record<string, boolean> = {};
  for (const item of CONFIGS) map[item.id] = item.defaultOn;
  return map;
}

export function sourceLabel(source: CatalogItem["source"]) {
  if (source === "winget") return "winget";
  if (source === "windows-update") return "Windows Update";
  return "файл";
}
